---
  - name: update ca-trust debian
    shell: /usr/sbin/update-ca-certificates
    when: ansible_os_family == 'Debian'

  - name: update ca-trust redhat
    shell: /bin/update-ca-trust
    when: ansible_os_family == 'RedHat'
